### PR TITLE
 v1.0.1 automate npm deployment and tests

### LINKED ISSUE #17: Automate Code Coverage
This project should report its code coverage to CodeCov, or something similar.

### PR DESCRIPTION
**Pull request by peterdemartini**
Additionally, the code has been updated with the linter and `index.js` was fixed to respect the linting.

Resolves #17 #16 #15

### CODE REVIEW

**Comment by peterdemartini** [comment]
Resolves #16 #15

**Review by kstaken — APPROVED** [review]
LGTM but one check is still failing. Should merging be held?

**Comment by peterdemartini** [comment]
I need to merge in the changes from master. I will do that tomorrow

**Comment by peterdemartini** [comment]
When this is pulled in, it will probably best to squash it into on commit

**Pull request merged**
