### PR TITLE
refactered code and waits for connections to come back up

### PR DESCRIPTION
**Pull request by jsnoble**

### CODE REVIEW

**Comment by jsnoble** [comment]
This is for issue https://github.com/terascope/teraslice/issues/632 of teraslice

**Comment by kstaken** [comment]
I tested this hitting `/txt/jobs`

Stopping elasticsearch results in this while it's down:

```
{
    "error": 500,
    "message": "Error getting all jobs, error: invoking elasticsearch_api _performSearch resulted in a runtime error: Error: No Living connections\n    at sendReqWithConnection (/Users/kstaken/projects/opensource/terafoundation/node_modules/elasticsearch/src/lib/transport.js:207:15)\n    at next (/Users/kstaken/projects/opensource/terafoundation/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)\n    at nextTickCallbackWith0Args (node.js:489:9)\n    at process._tickDomainCallback (node.js:459:13)"
}
```

Restarting elasticsearch results in the following error on the same endpoint.

```
{
    "error": 500,
    "message": "Error getting all jobs, error: invoking elasticsearch_api _performSearch resulted in a runtime error: error: undefined undefined on index: undefined"
}
```

**Comment by kstaken** [comment]
That error occurs while the target index is in recovery. Once it comes out of recovery the endpoint starts to work again. May need to look at why we're not getting a good error in this case.

Elasticsearch throws an exception on the request.

```
[2018-01-31T17:39:17,746][WARN ][r.suppressed             ] path: /teracluster__jobs/_search, params: {q=job_id:*, size=10000, index=teracluster__jobs, sort=_updated:desc}
org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:271) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:129) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:240) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.action.search.InitialSearchPhase.onShardFailure(InitialSearchPhase.java:88) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.action.search.InitialSearchPhase.run(InitialSearchPhase.java:135) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:143) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.start(AbstractSearchAsyncAction.java:113) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.action.search.TransportSearchAction.executeSearch(TransportSearchAction.java:308) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:186) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:65) ~[elasticsearch-5.5.0.jar:5.5.0]

```

**Comment by kstaken** [comment]
Going ahead with this merge as the underling problem is in the error_parser module. The message returned from ES has an empty `root_cause` array which the error_parser uses to fill out the message.

**Pull request merged**
